"""empty message

Revision ID: 5d2b1b74e7b0
Revises: 74308b397182
Create Date: 2024-07-19 15:42:07.744821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2b1b74e7b0'
down_revision = '74308b397182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellidos', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.Enum('hombre', 'mujer', 'desconocido', name='genero_tipo'), nullable=True),
    sa.Column('nacimiento', sa.Date(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('color_pelo', sa.String(length=50), nullable=True),
    sa.Column('color_ojos', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('temperatura', sa.String(length=200), nullable=True),
    sa.Column('diametro', sa.Integer(), nullable=True),
    sa.Column('gravedad', sa.Integer(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.Column('superficie_agua', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellidos', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=200), nullable=True),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('precio', sa.String(length=200), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('pilotos', sa.Integer(), nullable=True),
    sa.Column('pasajeros', sa.Integer(), nullable=True),
    sa.Column('velocidad', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('consumibles', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('favoritos',
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('vehiculo_id', 'personaje_id', 'planeta_id', 'usuario_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('favoritos')
    op.drop_table('vehiculos')
    op.drop_table('usuario')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
